### ISSUE TITLE
error: failed to run custom build command for `wry v0.24.1`

### ISSUE THREAD

**Issue by harisahmed05** [logankeenan/mobile-test#1]
Hello! I found you from [here](https://github.com/tauri-apps/wry/issues/834). You said it works for you. Could you please share the details that how you fixed the mismatch between versions? (I guess, that is the issue here)

I tried your project. Just changed the identifier, `"com.tauri.dev"` to `"com.test.dev"` in `tauri.conf.json` file.

**The logs:**
```zsh
error: failed to run custom build command for `wry v0.24.1 (https://github.com/tauri-apps/wry?branch=dev#87216c7f)`e

Caused by:
  process didn't exit successfully: `/home/shanto/Projects/mobile-test/src-tauri/target/release/build/wry-d4c371cf925f3780/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=WRY_ANDROID_PACKAGE
  cargo:rerun-if-env-changed=WRY_ANDROID_LIBRARY
  cargo:rerun-if-env-changed=WRY_ANDROID_KOTLIN_FILES_OUT_DIR

  --- stderr
  thread 'main' panicked at '`WRY_ANDROID_PACKAGE` is not set, which is needed to generate the kotlin files for android.', /home/shanto/.cargo/git/checkouts/wry-0ba07c7b81cd1a87/87216c7/build.rs:19:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
       Error `Failed to run `cargo build`: Command "cargo build --package mobile-test --manifest-path /home/shanto/Projects/mobile-test/src-tauri/Cargo.toml --target aarch64-linux-android --features custom-protocol --release --color always" didn't complete successfully, exiting with code 101.

FAILURE: Build failed with an exception.
```
**Command used:**
`cargo tauri android build`

**Versions:**
`cargo tauri --version` : `tauri-cli 2.0.0-alpha.0`

Looking forward for your reply. Thanks in advance!

**Comment by logankeenan** [comment]
@harisahmed05 

It might be because your tauri-cli version is different from what I used, tauri-cli 2.0.0-alpha.1.  See this [comment](https://github.com/tauri-apps/wry/issues/834#issuecomment-1382908498) to install the latest version.

**Comment by sito8943** [comment]
I was getting the same error after changed the identifier in the file "tauri.conf.json" from "com.tauri.dev" to own identifier. I just returned to the default value and it fixed "com.tauri.dev"

**Comment by logankeenan** [comment]
Oh, I miss read you original comment. I’m glad it’s working for you!
